# Generated by Django 4.2.5 on 2023-09-07 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'todo', 'verbose_name_plural': 'todos'},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='users',
        ),
        migrations.AddField(
            model_name='todo',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatooor', to='todo_app.projectuser', verbose_name='Пользователи'),
        ),
    ]
